name: Deploy Azure Functions (Python, Linux)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Deploy; server-side Oryx will build requirements.txt on Azure
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "azca-itsupport-funcwin"   # e.g. azca-itsupport-func
          package: "."
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
